#!/bin/sh

set -eu
export LC_ALL=C

IMG_IN=${1:?}
IMG_OUT=${2:-${IMG_IN%.*}.gif}
IMG_SIZE=${3:-256x256}

TMP_DIR=$(mktemp -d)
trap 'rm -rf "${TMP_DIR:?}"' EXIT

# Generate initial image
IMG_REFERENCE="${TMP_DIR:?}"/ref.png
convert -alpha set -scale "${IMG_SIZE:?}" "${IMG_IN:?}" "${IMG_REFERENCE:?}"
IMG_SIZE=$(identify -ping -format '%[fx:w]x%[fx:h]' "${IMG_REFERENCE:?}")!

# Generate frames
IMG_FRAMES=
i=0; while [ "${i:?}" -le 85 ]; do
	printf '\r\033[K%s' "Generating frames... $((i*100/85))%"
	IMG_FRAME="${TMP_DIR:?}"/"${i:?}".png
	IMG_FRAMES="${IMG_FRAMES?} ${IMG_FRAME:?}"
	convert -alpha set -liquid-rescale "$((100-i))%" "${IMG_REFERENCE:?}" "${IMG_FRAME:?}"
	convert -alpha set -scale "${IMG_SIZE:?}" "${IMG_FRAME:?}" "${IMG_FRAME:?}"
	i=$((i+1))
done

# Merge frames
printf '\n%s\n' 'Merging frames...'
# shellcheck disable=SC2086
convert -alpha set -dispose previous -coalesce -delay 6 -loop 0 ${IMG_FRAMES:?} "${IMG_OUT:?}"
